# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "protein_inference"
description: Subworkflow for protein inference from peptide identifications
keywords:
  - protein
  - inference
  - proteomics
  - peptides
components:
  - protein/inference/epifany
  - protein/inference/generic
  - id/filter
input:
  - ch_input:
      type: file
      description: |
        Channel containing input files for protein inference
output:
  - ch_protein_results:
      type: file
      description: |
        Channel containing protein inference results
  - versions:
      type: file
      description: |
        Software versions used in this subworkflow
authors:
  - "@bigbio"
maintainers:
  - "@bigbio" 