# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "psm_rescoring"
description: Subworkflow for PSM rescoring using various algorithms
keywords:
  - psm
  - rescoring
  - proteomics
  - scoring
components:
  - percolator
  - msrescore/features
  - get/sample
  - id/merger
  - id/ripper
  - spectrum/features
  - psm/clean
input:
  - ch_input:
      type: file
      description: |
        Channel containing input files for PSM rescoring
output:
  - ch_rescored_results:
      type: file
      description: |
        Channel containing rescored PSM results
  - versions:
      type: file
      description: |
        Software versions used in this subworkflow
authors:
  - "@bigbio"
maintainers:
  - "@bigbio" 