# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "psm_fdr_control"
description: Subworkflow for PSM-level false discovery rate control
keywords:
  - psm
  - fdr
  - discovery
  - rate
  - proteomics
components:
  - false_discovery_rate
  - id_filter
input:
  - ch_input:
      type: file
      description: |
        Channel containing input files for FDR control
output:
  - ch_fdr_results:
      type: file
      description: |
        Channel containing FDR-controlled results
  - versions:
      type: file
      description: |
        Software versions used in this subworkflow
authors:
  - "@bigbio"
maintainers:
  - "@bigbio"
