# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "feature_mapper"
description: Subworkflow for mapping features across different runs and conditions
keywords:
  - feature
  - mapping
  - alignment
  - proteomics
components:
  - isobaric/analyzer
  - id/mapper
input:
  - ch_input:
      type: file
      description: |
        Channel containing input files for feature mapping
output:
  - ch_mapped_features:
      type: file
      description: |
        Channel containing mapped features
  - versions:
      type: file
      description: |
        Software versions used in this subworkflow
authors:
  - "@bigbio"
maintainers:
  - "@bigbio" 