# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "protein_quant"
description: Subworkflow for protein quantification from MS data
keywords:
  - protein
  - quantification
  - proteomics
  - ms
components:
  - id/conflict/resolver
  - protein/quantifier
  - msstats/converter
input:
  - ch_input:
      type: file
      description: |
        Channel containing input files for protein quantification
output:
  - ch_quant_results:
      type: file
      description: |
        Channel containing protein quantification results
  - versions:
      type: file
      description: |
        Software versions used in this subworkflow
authors:
  - "@bigbio"
maintainers:
  - "@bigbio"
