# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "phospho_scoring"
description: Subworkflow for phosphorylation site scoring and localization
keywords:
  - phosphorylation
  - scoring
  - localization
  - proteomics
components:
  - id/score/switcher
  - luciphor
input:
  - ch_input:
      type: file
      description: |
        Channel containing input files for phospho scoring
output:
  - ch_phospho_results:
      type: file
      description: |
        Channel containing phosphorylation scoring results
  - versions:
      type: file
      description: |
        Software versions used in this subworkflow
authors:
  - "@bigbio"
maintainers:
  - "@bigbio"
